# Generated by Django 5.1.2 on 2024-11-21 09:35

from django.db import migrations


def migrate_camera_preset_to_position_preset(apps, schema_editor):
    CameraPreset = apps.get_model("facility", "CameraPreset")
    PositionPreset = apps.get_model("camera", "PositionPreset")

    camera_presets = CameraPreset.objects.all()

    position_presets = [
        PositionPreset(
            external_id=preset.external_id,
            name=preset.name,
            asset_bed=preset.asset_bed,
            position=preset.position,
            created_by=preset.created_by,
            updated_by=preset.updated_by,
            is_migrated=preset.is_migrated,
        )
        for preset in camera_presets
    ]

    PositionPreset.objects.bulk_create(position_presets)


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_camera_preset_to_position_preset),
    ]
