# Generated by Django 5.1.2 on 2024-11-21 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_auto_20241121_1505'),
        ('facility', '0469_delete_camerapreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionpreset',
            name='asset_bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camera_presets', to='facility.assetbed'),
        ),
    ]
