# Generated by Django 5.1.3 on 2024-12-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_auto_20241206_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionpreset',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='positionpreset',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
