name: Run Tests with Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the ohcnetwork/care repository
      - name: Checkout ohcnetwork/care repository
        uses: actions/checkout@v3
        with:
          repository: ohcnetwork/care

      # Update the plug_config.py file with the required content
      - name: Update plug_config.py
        run: |
          branch_name=${GITHUB_REF_NAME}
          cat > ./plug_config.py << 'EOL'
from plugs.manager import PlugManager
from plugs.plug import Plug

camera_plugin = Plug(
    name="camera",
    package_name="git+https://github.com/ohcnetwork/care_camera_asset.git",
    version="@${branch_name}",
    configs={},
)

plugs = [camera_plugin]

manager = PlugManager(plugs)
EOL

      # Build and start Docker containers
      - name: Build and start Docker containers
        run: |
          make up     

      # Run Django management command tests
      - name: Run Django management command tests
        run: |
          docker compose exec backend bash -c "python manage.py test camera --keepdb --parallel --shuffle"
