name: Run Tests with Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the DraKen0009/care repository
      - name: Checkout ohcnetwork/care repository
        uses: actions/checkout@v3
        with:
          repository: ohcnetwork/care
          ref: adding-camera-plugin

      # Build and start Docker containers
      - name: Build and start Docker containers
        run: |
          make up

      # Install plugins inside the backend container
      - name: Run install_plugins.py
        run: |
          docker compose exec backend bash -c "python install_plugins.py"

      Run tests using `make test`
      - name: Run `make test`
        run: make test

      # Run Django management command tests
      - name: Run Django management command tests
        run: |
          docker compose exec backend bash -c "python manage.py test camera --keepdb --parallel --shuffle"
